#
# MTAF Simplified
#
# NOTICE OF LICENSE
#
# This source file is subject to the Academic Free License (AFL 3.0)
# that is bundled with this package in the file LICENSE_AFL.txt.
# It is also available through the world-wide-web at this URL:
# http://opensource.org/licenses/afl-3.0.php
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to vash.igor(at)gmail.com so we can send you a copy immediately.
#
# DISCLAIMER
#
# The Original Work is provided under this License on an "AS IS" BASIS and WITHOUT WARRANTY,
# either express or implied, including, without limitation, the warranties of non-infringement,
# merchantability or fitness for a particular purpose.
#
# @category    tests
# @package     selenium
# @subpackage  test-data
# @author      Igor Tkachenko <vash.igor(at)gmail.com>
# @copyright   Copyright (c) 2013 Igor Tkachenko (https://github.com/vashigor/taf)
# @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
#
---
#Manage System Configuration

# 'System Configuration' page
system_configuration:
    uimap: &system_configuration_uimap
        form:
            tabs:
                -
                    sales_tax:
                        xpath: //dd/a[contains(@href, 'edit/section/tax/')]

system_configuration_tabs:
    uimap: *system_configuration_uimap

system_configuration_website:
    uimap: *system_configuration_uimap

system_configuration_store:
    uimap: *system_configuration_uimap

system_configuration_country:
    uimap: *system_configuration_uimap